-- Drop and create the students table

drop table students if exists;
create table students (
    id integer generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    email varchar(100) not null unique
);

-- Drop and create the subjects table

drop table subjects if exists;
create table subjects (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    description varchar(255),
    lecturer varchar(100)
);

-- Drop and create the grades table

drop table grades if exists;
create table grades (
    id integer generated by default as identity primary key,
    student_id integer not null,
    subject_id integer not null,
    grade_value varchar(10) not null,
    grade_date date,
    foreign key (student_id) references students(id),
    foreign key (subject_id) references subjects(id)
); 